control_hospital/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from doctores import views

urlpatterns = [
    url(r'^admin/', include(admin.site.urls)),
    url(r'^$', views.home_page, name='home'),
    url(r'^lists/la-unica-lista-en-el-mundo/$', views.view_list, name='lista'),
    url(r'^doctores/new$', views.nuevo_doctor, name='nuevo_doctor'),
]

doctores/models.py
from django.db import models


class Doctor(models.Model):
    nombre = models.TextField(default='')
    apellido = models.TextField(default='', blank=True)

doctores/views.py
from django.shortcuts import render, redirect
from doctores.models import Doctor


def home_page(request):
    return render(request, 'home.html')


def view_list(request):
    doctores = Doctor.objects.all()
    return render(request, 'list.html', {'doctores': doctores})


def nuevo_doctor(request):
    Doctor.objects.create(nombre=request.POST['nombre_doc'])
    return redirect('/lists/la-unica-lista-en-el-mundo/')

doctores/templates/home.html
<body>
		<h1>Nuevo Control Hospital</h1>
		<form method="POST" action="/doctores/new">
			<input name="nombre_doc" id="id_nombre" placeholder="Nombre" />
			{% csrf_token %}
		</form>
</body>

doctores/templates/list.html
<html>
	<head>
		<title>Control Hospital</title>
	</head>
	<body>
		<h1>Control Hospital</h1>
		<form method="POST" action="/">
			<input name="nombre_doc" id="id_nombre" placeholder="Nombre" />
			
			{% csrf_token %}
		</form>
		<table id="id_doctors_table">
			{% for doctor in doctores %}
				<tr><td>{{ forloop.counter }}: {{ doctor.nombre }}</td></tr>
			{% endfor %}
		</table>
	</body>
</html>